version: '3.8'

services:
  postgres:
    image: postgres-14
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gerenciamentousuarios
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  apiteste:
    build: .
    container_name: apiteste
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/gerenciamentousuarios
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:

